//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaspMat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaspMat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddZeros.
        /// </summary>
        public static string _ADD_ZEROS {
            get {
                return ResourceManager.GetString("_ADD_ZEROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string _CELL_DEFAULT {
            get {
                return ResourceManager.GetString("_CELL_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cols.
        /// </summary>
        public static string _COLS {
            get {
                return ResourceManager.GetString("_COLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON|*.json|*|*.*.
        /// </summary>
        public static string _FILE_FILTER {
            get {
                return ResourceManager.GetString("_FILE_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewMatDialog.
        /// </summary>
        public static string _NEW_MAT_DIALOG {
            get {
                return ResourceManager.GetString("_NEW_MAT_DIALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        public static string _ROWS {
            get {
                return ResourceManager.GetString("_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string _ZERO {
            get {
                return ResourceManager.GetString("_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add zeros..
        /// </summary>
        public static string ADD_ZEROES {
            get {
                return ResourceManager.GetString("ADD_ZEROES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithms.
        /// </summary>
        public static string ALGORITHMS {
            get {
                return ResourceManager.GetString("ALGORITHMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot inverse this matrix, because its determinant is zero..
        /// </summary>
        public static string DET_ZERO {
            get {
                return ResourceManager.GetString("DET_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row echelon.
        /// </summary>
        public static string ECHELON {
            get {
                return ResourceManager.GetString("ECHELON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elementary operations.
        /// </summary>
        public static string ELEMENTARY_MAT_OP {
            get {
                return ResourceManager.GetString("ELEMENTARY_MAT_OP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New matrix.
        /// </summary>
        public static string ENTER_MATRIX {
            get {
                return ResourceManager.GetString("ENTER_MATRIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The numer of rows or columns of this matrix indicates it does not support the requested operation..
        /// </summary>
        public static string ERR_MAT_BAD_SHAPE {
            get {
                return ResourceManager.GetString("ERR_MAT_BAD_SHAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation can be performed on a square matrix only..
        /// </summary>
        public static string ERR_MAT_NO_SQUARE {
            get {
                return ResourceManager.GetString("ERR_MAT_NO_SQUARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left matrix has different amount of columns than right of rows ..
        /// </summary>
        public static string ERR_MULTIPLY_MAT_MISMATCH {
            get {
                return ResourceManager.GetString("ERR_MULTIPLY_MAT_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No integer supplied..
        /// </summary>
        public static string ERR_NO_INTS {
            get {
                return ResourceManager.GetString("ERR_NO_INTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select exactly {0} row(s)..
        /// </summary>
        public static string ERR_ROWS {
            get {
                return ResourceManager.GetString("ERR_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied string is not in any of the supported formats: {0}.
        /// </summary>
        public static string ERR_STRING_FORMAT {
            get {
                return ResourceManager.GetString("ERR_STRING_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add or subtract matrices with different shapes..
        /// </summary>
        public static string ERR_SUM_SUB_MAT_MISMATCH {
            get {
                return ResourceManager.GetString("ERR_SUM_SUB_MAT_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many integers supplied..
        /// </summary>
        public static string ERR_TOO_MANY_INTS {
            get {
                return ResourceManager.GetString("ERR_TOO_MANY_INTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matrix must have at least {0} column(s) and {1} row(s)..
        /// </summary>
        public static string ERR_TOO_SMALL_MAT {
            get {
                return ResourceManager.GetString("ERR_TOO_SMALL_MAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity matrix.
        /// </summary>
        public static string IDENTITY_MAT {
            get {
                return ResourceManager.GetString("IDENTITY_MAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill with zeros..
        /// </summary>
        public static string IN_ADD_ZEROS {
            get {
                return ResourceManager.GetString("IN_ADD_ZEROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns:.
        /// </summary>
        public static string IN_COLUMNS {
            get {
                return ResourceManager.GetString("IN_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows:.
        /// </summary>
        public static string IN_ROWS {
            get {
                return ResourceManager.GetString("IN_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert identity.
        /// </summary>
        public static string INSERT_I {
            get {
                return ResourceManager.GetString("INSERT_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string LEFT {
            get {
                return ResourceManager.GetString("LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string LOAD {
            get {
                return ResourceManager.GetString("LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load matrix.
        /// </summary>
        public static string LOAD_MAT {
            get {
                return ResourceManager.GetString("LOAD_MAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix slicing.
        /// </summary>
        public static string MAT_HALF {
            get {
                return ResourceManager.GetString("MAT_HALF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix.
        /// </summary>
        public static string MATRIX {
            get {
                return ResourceManager.GetString("MATRIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduced row echelon.
        /// </summary>
        public static string REDUCED {
            get {
                return ResourceManager.GetString("REDUCED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove half.
        /// </summary>
        public static string REMOVE_HALF {
            get {
                return ResourceManager.GetString("REMOVE_HALF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string RIGHT {
            get {
                return ResourceManager.GetString("RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row(s).
        /// </summary>
        public static string ROW {
            get {
                return ResourceManager.GetString("ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save matrix.
        /// </summary>
        public static string SAVE_MAT {
            get {
                return ResourceManager.GetString("SAVE_MAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalar:.
        /// </summary>
        public static string SCALAR {
            get {
                return ResourceManager.GetString("SCALAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string SCALE {
            get {
                return ResourceManager.GetString("SCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiply row {0} by {1}..
        /// </summary>
        public static string STEP_MULTIPLY_ROW {
            get {
                return ResourceManager.GetString("STEP_MULTIPLY_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add row {0} multiplied by {1} to row {2}..
        /// </summary>
        public static string STEP_SUM_ROWS {
            get {
                return ResourceManager.GetString("STEP_SUM_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap rows {0} and {1}..
        /// </summary>
        public static string STEP_SWAP_ROWS {
            get {
                return ResourceManager.GetString("STEP_SWAP_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps.
        /// </summary>
        public static string STEPS {
            get {
                return ResourceManager.GetString("STEPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap rows.
        /// </summary>
        public static string SWAP_ROWS {
            get {
                return ResourceManager.GetString("SWAP_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RaspMat.
        /// </summary>
        public static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transposition.
        /// </summary>
        public static string TRANSPOITION {
            get {
                return ResourceManager.GetString("TRANSPOITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transpose.
        /// </summary>
        public static string TRANSPOSE {
            get {
                return ResourceManager.GetString("TRANSPOSE", resourceCulture);
            }
        }
    }
}
